import type { Recommendation } from './types'

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    title: 'Breaking Bad',
    release_year: 2008,
    episode_runtime_minutes: 47,
    genres: ['Crime', 'Drama', 'Thriller'],
    tvdb_poster_thumbnail_url: 'https://artworks.thetvdb.com/banners/v4/series/81189/posters/61222c5f7f8b8.jpg',
    tvdb_show_url: 'https://www.thetvdb.com/series/breaking-bad',
    streaming_platforms: ['Netflix', 'Amazon Prime Video'],
    average_user_rating: 9.2,
    imdb_rating: 9.5,
    comedy_score: 2,
    horror_score: 1,
    action_score: 7,
    drama_score: 10,
    suspense_score: 10,
    romance_score: 3,
    reason: 'A gripping drama about transformation with excellent writing and intense suspense.',
  },
  {
    title: 'The Office',
    release_year: 2005,
    episode_runtime_minutes: 22,
    genres: ['Comedy', 'Drama'],
    tvdb_poster_thumbnail_url: 'https://artworks.thetvdb.com/banners/v4/series/84912/posters/5614c47fa1434.jpg',
    tvdb_show_url: 'https://www.thetvdb.com/series/the-office',
    streaming_platforms: ['Netflix', 'Peacock'],
    average_user_rating: 8.9,
    imdb_rating: 9.0,
    comedy_score: 10,
    horror_score: 0,
    action_score: 1,
    drama_score: 6,
    suspense_score: 2,
    romance_score: 5,
    reason: 'A mockumentary comedy that perfectly blends humor with heartfelt character moments.',
  },
  {
    title: 'Stranger Things',
    release_year: 2016,
    episode_runtime_minutes: 50,
    genres: ['Drama', 'Fantasy', 'Horror'],
    tvdb_poster_thumbnail_url: 'https://artworks.thetvdb.com/banners/v4/series/269641/posters/60d75c3a5c49f.jpg',
    tvdb_show_url: 'https://www.thetvdb.com/series/stranger-things',
    streaming_platforms: ['Netflix'],
    average_user_rating: 8.7,
    imdb_rating: 8.7,
    comedy_score: 3,
    horror_score: 7,
    action_score: 8,
    drama_score: 8,
    suspense_score: 9,
    romance_score: 4,
    reason: 'An enthralling supernatural mystery with 80s nostalgia and excellent production.',
  },
  {
    title: 'The Crown',
    release_year: 2016,
    episode_runtime_minutes: 60,
    genres: ['Biography', 'Drama', 'History'],
    tvdb_poster_thumbnail_url: 'https://artworks.thetvdb.com/banners/v4/series/280360/posters/5f6f1c8a4c81a.jpg',
    tvdb_show_url: 'https://www.thetvdb.com/series/the-crown',
    streaming_platforms: ['Netflix'],
    average_user_rating: 8.6,
    imdb_rating: 8.6,
    comedy_score: 1,
    horror_score: 0,
    action_score: 3,
    drama_score: 9,
    suspense_score: 6,
    romance_score: 4,
    reason: 'An opulent period drama that captures the complexity of royal life with stellar acting.',
  },
  {
    title: 'Ted Lasso',
    release_year: 2020,
    episode_runtime_minutes: 35,
    genres: ['Comedy', 'Drama', 'Sport'],
    tvdb_poster_thumbnail_url: 'https://artworks.thetvdb.com/banners/v4/series/385375/posters/619e9de30f4ba.jpg',
    tvdb_show_url: 'https://www.thetvdb.com/series/ted-lasso',
    streaming_platforms: ['Apple TV+'],
    average_user_rating: 8.8,
    imdb_rating: 8.8,
    comedy_score: 9,
    horror_score: 0,
    action_score: 2,
    drama_score: 7,
    suspense_score: 2,
    romance_score: 5,
    reason: 'An uplifting comedy about believing in people and the power of optimism and kindness.',
  },
]
